# .goreleaser.yml
# Build customization
builds:
  - dir: apigee-istio
    binary: apigee-istio
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archives:
  - format: tar.gz
    replacements:
      darwin: macOS
      amd64: 64-bit
    files:
      - LICENSE
      - README.md
      - samples/**/*
      - install/**/*
release:
  draft: true
  prerelease: true
